

# Site Settings
title: 						"NovayNotes"
email: 						"novay@about.me"
description: 				"Based on Astro Tempalate by EckoThemes which subtitute my current template on my personal blog."
baseurl: 					""
url: 						"http://novay.github.io/contoh-jekyll-template/"
logourl: 					"http://novay.github.io/contoh-jekyll-template//assets/img/bloglogo.jpg"		
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Noviyanto Rachmady"
author_url: 				"http://novay.web.id"
author_bio: 				"Noviyanto Rachmady has built a career and reputation by breaking the rules. Novay's shoot-from-the-hip style has made him an effective programmer and a slick pirates."
author_email: 				"novay@about.me"
author_image: 				"http://novay.github.io/contoh-jekyll-template//assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/novaymawbowo"
facebook_url: 				"http://facebook.com/novaymawbowo"
github_url:  				"http://github.com/novay"
youtube_url:  				"http://youtube.com/noviyantorachmady"
dribbble_url:  				"http://dribbble.com/novay"
googleplus_url: 			"http://google.com/+novaymawbowo"
instagram_url:  			"http://instagram.com/__novay"
pinterest_url:  			"http://pinterest.com/novay"
linkedin_url:  				"http://linkedin.com/novay"


# Theme Settings
theme_disqus_shortname: 	"novay-notes"
theme_google_comments: 		false
theme_analytics_id: 		"UA-28282324-1"
theme_analytics_domain: 	"novay.web.id"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

